### ISSUE TITLE
feat: where should the data prep functions live that are specific to the dashboard?

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/workflow.pacta.dashboard#10]
From what has been implemented so far, we're using the existing data structures that are generated by `pacta.portfolio.report`, however, for some plots we will need to generate new datasets because they will be new plots. Where should the functions generating those live? Should we create a new package for them? 

Also - at the moment we translate the existing datasets but since for now I assume we will only have the dashboard available in English, I don't think there is a need for translations for the new charts. Do you agree @jdhoffa ?

**Comment by AlexAxthelm** [comment]
I would say this repo/package is the right spot for those.

**Comment by MonikaFu** [comment]
@AlexAxthelm thanks! In principle I agree. The only problem I have with this solution is that it violates our intention to not use `workflow.*`-type repos as packages.

**Comment by AlexAxthelm** [comment]
🤷 All the workflow repos are packages. I think doing some reformatting of data is in-scope here (so long isn't doing the actual analysis).

**Comment by jdhoffa** [comment]
Agree that at this stage any data preparation functions that are additional to what is required by the report should live in this repository. 

We may decide at some point to refactor a utility package out of this to keep track of those function, but for now I think they are fine here

**Comment by jdhoffa** [comment]
Also agree that at this stage, we do not need translations (although we very likely will at some point!)

**Comment by jdhoffa** [comment]
Let me know if those answers are sufficient to close this issue

**Comment by MonikaFu** [comment]
Sufficient, thank you @jdhoffa

**Comment by MonikaFu** [comment]
Closing this issue given that decision has been made and we have a new issue tracking the creation of the `data_prep`: #11
