### ISSUE TITLE
Bug: align scenario names between company bubble and techmix for WEO2023

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/workflow.pacta.dashboard#23]
In one plot the scenario name is NZE 2050 (techmix) and in the other it is NZE_2050 (bubble chart). 

To reproduce you can go to https://rmi-pacta.github.io/pacta-dashboard-svelte/ -> Company-level Analysis tab -> Go! -> change scenario for WEO2023 to NZE 2050 and then NZE_2050

I'm not sure if it is a data artifact of a problem coming from how the data is being prepared.

**Comment by cjyetman** [comment]
both `prep_key_bars_portfolio()` and `prep_key_bars_company()` have this line that substitutes " " for "_" in the scenario names, which they inherited from `pacta.portfolio.report:::prep_key_bars_portfolio()` and `pacta.portfolio.report:::prep_key_bars_company()`

https://github.com/RMI-PACTA/workflow.pacta.dashboard/blob/c224cfb6a6487bbf492be8cd7e9835389b8753cc/main.R#L342

https://github.com/RMI-PACTA/workflow.pacta.dashboard/blob/c224cfb6a6487bbf492be8cd7e9835389b8753cc/main.R#L396

https://github.com/RMI-PACTA/pacta.portfolio.report/blob/5f002dc1267fe9ac66b379642d5465ec636bd30f/R/prep_key_bars_company.R#L70

https://github.com/RMI-PACTA/pacta.portfolio.report/blob/5f002dc1267fe9ac66b379642d5465ec636bd30f/R/prep_key_bars_portfolio.R#L60

That doesn't seem desirable here, so I'll submit a PR that removes those lines from the functions in this repo.
