### ISSUE TITLE
feat: compress all output json files into a `archive.zip`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.pacta.dashboard#27]
In the dashboard, we wish to allow users to download the input datasets. This would facilitate that.

**Comment by jdhoffa** [comment]
It was not. 
In https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/82 (a different repo) a button was created that allows users to download a .zip archive. 

This issue tracks the actual creation of that .zip archive (if it doesn't exist, the button won't do anything). 

Acceptance criteria: 

- [ ] workflow.pacta.dashboard creates a .zip of all .json assets after a run is complete
- [ ] (Nice-to-have) the .zip contains `.csv` files rather than `.json` files (probably more user friendly)

**Comment by cjyetman** [comment]
huh... currently on https://rmi-pacta.github.io/pacta-dashboard-svelte/ if I click the "Save Data" button it downloads an "archive.zip" which contains JSON files.

**Comment by jdhoffa** [comment]
Indeed, because the `archive.zip` was manually created and merged into the `sample-data` directory that is used to spin up that dashboard. 
It is out of sync with this repo, that's what this tracking issue is for 😊

**Comment by AlexAxthelm** [comment]
Disabled as part of #35

**Comment by jdhoffa** [comment]
I was able to locally reproduce the error mentioned in #35 :
``` r
workflow.pacta.dashboard-1  | Error in write_delim(x, file, delim = ",", na = na, append = append, col_names = col_names,  : 
workflow.pacta.dashboard-1  |   is.data.frame(x) is not TRUE
workflow.pacta.dashboard-1  | Calls: <Anonymous> ... zip_outputs -> %>% -> <Anonymous> -> write_delim -> stopifnot
workflow.pacta.dashboard-1  | Execution halted
workflow.pacta.dashboard-1 exited with code 1
```

Investigating.

**Comment by jdhoffa** [comment]
The error occurs because the datasets `data_company_bubbles.json` and `data_techexposure.json` are empty. 

These empty JSON files are then read into R as a `list()` object, and the list object cannot be written to a `.csv` file. 

My recommendation here would be to add a check prior to calling `jsonlite::write_json()` every time in the script, and to not write an empty data frame in the first place, e.g. here:
https://github.com/RMI-PACTA/workflow.pacta.dashboard/blob/0ab208c3f09f3572d1d192a777327b50edc3df10/R/prepare_pacta_dashboard_data.R#L149-L157
