### ISSUE TITLE
feat: add `data_emissions_pie_bonds.json` and `data_emissions_pie_equity.json` output

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/workflow.pacta.dashboard#6]
New data input dependencies data_emissions_pie_bonds.json and data_emissions_pie_equity.json were introduced into pacta-dashboard-svelte in https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/20.

We need now ensure that this dataset is prepared properly in this repository.

The relevant preparation function can be found here:
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/R/prep_emissions_pie.R

FYI @AlexAxthelm @jdhoffa 

AB#11583

**Comment by jdhoffa** [comment]
ADO update:
Ticket has been added as child of: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10614

To be prioritized appropriately :-)
