### ISSUE TITLE
feat: add `data_techexposure_future.json` output

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/workflow.pacta.dashboard#8]
New data input dependencies data_techmix_future.json were introduced into pacta-dashboard-svelte in https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/31.

We need now ensure that this dataset is prepared properly in this repository.

The relevant preparation function can be found here:
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/R/prep_techexposure_future.R

FYI @AlexAxthelm @jdhoffa

AB#11687

**Comment by jdhoffa** [comment]
ADO update:
Ticket has been added as child of: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10614

To be prioritized appropriately :-)

**Comment by MonikaFu** [comment]
this is not necessary anymore because we're not going to show this plot in the dashboard.
