### ISSUE TITLE
feat: make company-level data filterable on scenario source, scenario and portfolio allocation

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/workflow.pacta.dashboard#9]
Once the company-level plots and data are implemented in the current shape that exists in the interactive report we need to limit the amount of filtering that is done in the respective `prep_*.R` functions so that the users can decide on scenario source, scenario and portfolio allocation themselves. Currently all these choices are done for the user by us. See relevant functions from `pacta.portfolio.report` for reference:

https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/R/prep_company_bubble.R
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/R/prep_key_bars_company.R

FYI @jdhoffa 

AB#11688

**Comment by jdhoffa** [comment]
ADO update:
Ticket has been added as child of: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10614

To be prioritized appropriately :-)

**Comment by jdhoffa** [comment]
Relevant data formats: 
https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/main/src/json/data_company_bubble.json
https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/main/src/json/data_techexposure_company_companies.json
